### ISSUE TITLE
training gpu

### ISSUE THREAD

**Issue by lingxitong** [mahmoodlab/UNI#27]
hello,can you tell me how many A100s you used,and how many hours you trianed,thanks very much

**Comment by Richarizardd** [comment]
HI @lingxitong 

We used 4x8 A100 80GB GPUs (4 nodes, each with 8 GPUs, trained with multi-node distributed training). This trained for 32 GPU hours (1024 GPU hours in total).

For more details, [see the model card for UNI on HF](https://huggingface.co/MahmoodLab/UNI#training-details).

**Comment by dt-yuhui** [comment]
@Richarizardd HI.

I noticed the hardware spec in **Supplementary Data Table 5** states "4x 80GB NVIDIA A100 GPUs were used for training."

Could you please confirm if this is a **typo**?

As you mentioned above, it should be: **4 nodes $\times$ 8 A100 GPUs/node** (for a total of 32 GPUs), rather than just 4 GPUs total.

<img width="1164" height="1042" alt="Image" src="https://github.com/user-attachments/assets/07520864-7cfc-4b1f-837c-1cc064f7942b" />
